name: starter_flutter_app
description: A production-ready Flutter starter template.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  # firebase_core: ^3.6.0
  # firebase_analytics: ^11.3.3
  # firebase_messaging: ^15.1.3
  # firebase_crashlytics: ^4.1.3

  # # Ads
  # google_mobile_ads: ^5.1.0

  # # In-App Purchase
  # in_app_purchase: ^3.2.0

  # Push (choose ONE)
  # onesignal_flutter: ^5.2.6

  # Engagement: review, share, home-screen widgets
  in_app_review: ^2.0.9
  share_plus: ^12.0.2
  home_widget: ^0.9.2

  # State Management
  provider: ^6.1.2
  go_router: ^17.2.3

  # Localization
  intl: ^0.20.2

  # Storage
  shared_preferences: ^2.3.2

  # Network / Utils
  connectivity_plus: ^6.0.5
  package_info_plus: ^8.1.0
  url_launcher: ^6.3.0
  animations: ^2.2.0
  flutter_screenutil: ^5.9.3
  permission_handler: ^12.0.1
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12

  # Dev tools
  flutter_launcher_icons: ^0.14.1
  change_app_package_name: ^1.5.0
  rename: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"